name: Experiment - Fire

on:
  workflow_dispatch:

jobs:
  woosh:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 3b1be9c7ea06f3f09e266e8722e9571f7017feaf

      - name: update tag
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          tag="1.0.0"
          git tag -f $tag 3b1be9c7ea06f3f09e266e8722e9571f7017feaf -m 'oit'
          git push -f origin $tag

      