name: Experiment - Fire

on:
  workflow_dispatch:
    inputs:
      run-test:
        type: boolean
        description: Run unit test

jobs:
  woosh:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    env:
      is_compare_coverage: ${{ github.workflow == 'Experiment- Fire' }}
    steps:
      - name: check bash
        run: |
          echo ${{ inputs.run-test }}
          echo ${{ env.is_compare_coverage }}

      - name: check dispatch input
        if: ${{ inputs.run-test }}
        run: echo "pass"

      - name: check env
        if: ${{ env.is_compare_coverage }}
        run: echo "pass"

      - name: check env true
        if: ${{ env.is_compare_coverage == true }}
        run: echo "pass"

      - name: check env true string
        if: ${{ env.is_compare_coverage == 'true' }}
        run: echo "pass"

      - name: check env false
        if: ${{ env.is_compare_coverage == false }}
        run: echo "pass"

      - name: check env false string
        if: ${{ env.is_compare_coverage == 'false' }}
        run: echo "pass"

