name: Experiment - Fire

on:
  workflow_dispatch:
    inputs:
      run-test:
        type: boolean
        description: Run unit test

jobs:
  woosh:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: create a new repository variable
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/variables \
          -d '{
              "name":"ELEMENT",
              "value":"fire"
            }'
