name: Update Sprint Branch

on:
  schedule:
    # - cron: "0 17 * * 2" #every tuesday midnight (GMT+7)
    - cron: "30 9 * * 4"

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      is_halfway: ${{ vars.IS_SPRINT_HALFWAY == 'true' }}
    steps:
      - name: check is sprint halfway
        id: check-next-value
        run: |
          if [ $is_halfway == "true" ]; then
            echo "result=false" >> $GITHUB_OUTPUT
          else
            echo "result=true" >> $GITHUB_OUTPUT
          fi
      
      - name: update is halfway value
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/variables/IS_SPRINT_HALFWAY \
          -d '{
              "value":"${{ steps.check-next-value.outputs.result }}"
            }'
 
  update:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ vars.IS_SPRINT_HALFWAY == 'false' }}
    steps:
      - name: setup
        id: setup
        run: |
          current_sprint="${{ vars.CURRENT_SPRINT }}"
          current_sprint_branch=sprint-$current_sprint

          next_sprint=$(($current_sprint+1))
          next_sprint_branch=sprint-$next_sprint

          echo "current_sprint_branch=$current_sprint_branch" >> $GITHUB_OUTPUT
          echo "next_sprint=$next_sprint" >> $GITHUB_OUTPUT
          echo "next_sprint_branch=$next_sprint_branch" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.setup.outputs.current_sprint_branch }}

      - name: create branch
        run: |
          git checkout -b ${{ steps.setup.outputs.next_sprint_branch }}
          git push origin ${{ steps.setup.outputs.next_sprint_branch }}

      - name: update current sprint value
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/variables/CURRENT_SPRINT \
          -d '{
              "value":"${{ steps.setup.outputs.next_sprint }}"
            }'

      