name: Update Tag

on:
  pull_request:
    types:
      - closed

jobs:
  publish_tags:
    # if: github.event.pull_request.merged && github.base_ref == 'main' && startsWith(github.head_ref, 'release/rc') 
    if: github.event.pull_request.merged && github.base_ref == 'experiment/ci-main' && startsWith(github.head_ref, 'release/rc') 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: get app version from pubspec.yaml
        id: get-app-version
        run: |
          app_version=$(cat ./app/pubspec.yaml | grep 'version' | cut -d ':' -f2 | cut -d '+' -f1 | sed 's/ //')
          echo "result=$app_version" >> $GITHUB_OUTPUT

      - name: release tag message
        id: release-tag-message
        # uses: Agriaku/agriaku_app_actions/release-tag@v1.6.0
        uses: syaiful-aa/actions-experiment/release-tag@v3.5.0
        with:
          pr_body: ${{ github.event.pull_request.body }}

      - name: create and push tag
        run: |
          git config user.email "syaiful.salam@agriaku.com"
          git config user.name "syaiful-bot"
          tag="${{ steps.get-app-version.outputs.result }}"
          # git tag -f $tag ${{ github.event.pull_request.head.sha }} -m $'${{steps.release-tag-message.outputs.message}}'
          # git tag -f $tag -m $'${{steps.release-tag-message.outputs.message}}'
          git push -f origin $tag